### ISSUE TITLE
Manual install feedback - Debian Bookworm LTS

### ISSUE THREAD

**Issue by b1u3y** [CounterpartyXCP/counterparty-core#1606] opened 2024-04-04 17:32 UTC
Feedback from manual install/upgrade on Debian LTS today...
(I know Debian isn't 'officially supported' and manual installation is not the go to method, let's call this testing or trying to add another supported OS/setup type in the future, Ubuntu is built on Debian, the two are not too dissimilar.) 

Commit 9b66701 v10.0.1

After pulling updates and reinstalling, kickstart fails with no on screen errors, errors were on screen before. 

Tailing the log shows TypeError: 'NoneType' object is not subscriptable re: counterpartylib/lib/backend/addrindexrs.py line 469 indexer_check_version @  = addrindexrs_version["result"]

It appears that force=0 or 1 changes nothing with my situation. Also appears that no connection is made to addrindexrs where (i think) previously kickstart attempts did connect to addrindexrs, or at least tried and showed something when tailing addrindexrs, but nothing now. 

‘Start’ does not work any more, but did work for me prior to today, it was just slow. Start now throws the same error as kickstart. 
I know kickstart is supposed to be deprecated, but this version has disabled start for me. 

‘Start’ is not taking the --bitcoind-dir= option at all. JA had a docker issue/question about something similar, --bitcoind-dir might not be a docker only problem. 

Counterparty is not currently ready to support a bitcoind install where the blocks are in a different directory than default, because counterparty assumes the /chainstate and /blocks directory have the same parent directory and counterpartyserver does not take bitcoind.conf settings into account. A bitcoind setup can move the blocks dir, but the chainstate directory stays in the bitcoin directory. Counterparty does not
currently have options that differentiate the bitcoindir, the blocks dir and the chainstate directory. 

Let me know if you have questions that can help you, the project or the team. Thanks.

**Comment by b1u3y** [comment] 2024-04-04 17:37
Not exactly a bug. Github defaulted the label to bug and ignored my suggested labels. 

"Testing", "Code Quality", and "Possible Bug" are the labels I recommended.

**Comment by b1u3y** [comment] 2024-04-04 18:01
Updated error from Matt's c8593f commit

  File "/home/b1u3y/.local/lib/python3.11/site-packages/counterpartylib/lib/backend/addrindexrs.py", line 551, in indexer_check_version
    addrindexrs_version = INDEXER_THREAD.send({"method": "server.version", "params": []})
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b1u3y/.local/lib/python3.11/site-packages/counterpartylib/lib/backend/addrindexrs.py", line 511, in send
    raise AddrIndexRsClientError(f"AddrIndexRsClient -- Error in response: {res['error']}")  # noqa: F821
          ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'AddrIndexRsClientError' is not defined

**Comment by adamkrellenstein** [comment] 2024-04-07 12:35
It sounds like the issue is an idiosyncratic bitcoind configuration and a bad error message. Since this code is all going to be deleted soon, going to make this a wontfix.

**Closed by adamkrellenstein** 2024-04-07 12:35 UTC
Labels: bug
