### ISSUE TITLE
V1 api regressions on 10.4

### ISSUE THREAD

**Issue by DerpHerpenstein** [CounterpartyXCP/counterparty-core#2274] opened 2024-09-28 02:49 UTC
Doing some testing and there appear to be some regressions on the latest api. 

First, one is pretty straight forward. make a create_send like this

`{
  method: 'create_send',
  params: {
    source: 'bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4',
    destination: 'bc1qnrjh84yc3v35grnp9fns42uymkt0ngygn5kl4p',
    asset: 'BTC',
    quantity: 14999,
    allow_unconfirmed_inputs: true,
    extended_tx_info: true,
    fee: 5044
  },
  jsonrpc: '2.0',
  id: 0
}`

the result is 
`
{"result": {"btc_in": 71747, "btc_out": 14999, "btc_change": 51704, "btc_fee": 5044, "unsigned_tx_hex": "0200000000010181a04f8ad522ce624af714db4ff8ae07055143cbba958400abf52fe57f3b9c1d2400000016001422a8870cac68d8633dd1a3ba560c388df14be86dffffffff02973a00000000000016001498e573d4988b23440e612a670aab84dd96f9a088f8c900000000000016001422a8870cac68d8633dd1a3ba560c388df14be86d02000000000000", "unsigned_pretx_hex": null, "data": null}, "id": 0, "jsonrpc": "2.0"}
`

the property unsigned_tx_hex was previously tx_hex.

Also, i haven't dug into this one, but there appears to be an issue with create_issuance as well
`
{
  method: 'create_issuance',
  params: {
    source: 'bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4',
    asset: 'A3949781344190282000',
    quantity: 1,
    divisible: false,
    description: 'STAMP:',
    lock: true,
    reset: false,
    allow_unconfirmed_inputs: true,
    extended_tx_info: true,
    fee: 41043
  },
  jsonrpc: '2.0',
  id: 0
}
`

This will throw a 500 internal server error. i haven't dug any further than that.

**Comment by adamkrellenstein** [comment] 2024-09-28 13:25
woops! we'll release a patch ASAP

**Comment by ouziel-slama** [comment] 2024-09-30 12:08
first fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2264/commits/491d4020fc7903ceaf235768e7e8199a136bf370

but can't reproduce the second:
```
curl -X POST http://127.0.0.1:4000/v1/       --user rpc:rpc       -H 'Content-Type: application/json; charset=UTF-8'      -H 'Accept: application/json, text/javascript'       --data-binary '{"method": "create_issuance", "params": {"source": "bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4", "asset": "A3949781344190282000", "quantity": 1, "divisible": false, "description": "STAMP:", "lock": true, "reset": false, "allow_unconfirmed_inputs": true, "extended_tx_info": true, "fee": 41043}, "jsonrpc": "2.0", "id": 0}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   851  100   530  100   321   1440    872 --:--:-- --:--:-- --:--:--  2318
{
  "result": {
    "btc_in": 71747,
    "btc_out": 0,
    "btc_change": 30704,
    "btc_fee": 41043,
    "data": "434e5452505254591636d07134a8ed391000000000000000010001005354414d503a",
    "tx_hex": "0200000000010181a04f8ad522ce624af714db4ff8ae07055143cbba958400abf52fe57f3b9c1d2400000016001422a8870cac68d8633dd1a3ba560c388df14be86dffffffff020000000000000000246a2207061014b1ac39f5d1ade275edc436401fa000976ebaf38a52dbb20ec55ae8f4ab6bf07700000000000016001422a8870cac68d8633dd1a3ba560c388df14be86d02000000000000",
    "pretx_hex": null
  },
  "id": 0,
  "jsonrpc": "2.0"
}
```

**Comment by ouziel-slama** [comment] 2024-09-30 12:09
probably already fixed with this https://github.com/CounterpartyXCP/counterparty-core/issues/2263

**Closed** 2024-09-30 12:43 UTC
Labels: bug
