### ISSUE TITLE
"Empty previous txlist_hash"

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1476] opened 2024-03-07 12:08 UTC

**Comment by ouziel-slama** [comment] 2024-03-08 11:53
Fixed

**Comment by adamkrellenstein** [comment] 2024-03-12 12:44
I just got this again, now on `mainnet`:
```
adam@api4:~/counterparty-core$ counterparty-server start
Running v10.0.0-alpha of Counterparty Core.
ERROR:root:SQLITE_LOG: recovered 1 frames from WAL file /home/adam/.local/share/counterparty/counterparty.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
[2024-03-11 16:40:09][INFO] Running v10.0.0-alpha of counterparty-server.
Writing log to file: `/home/adam/.cache/counterparty/log/server.log`
Writing API accesses log to file: `/home/adam/.cache/counterparty/log/server.access.log`
------------------------------ start ------------------------------

[2024-03-11 16:40:09][INFO] Connecting to address indexer.
[2024-03-12 11:16:48][INFO] Starting API Server.
[2024-03-12 11:16:49][INFO] Client major version number mismatch (9 ≠ 10).
[2024-03-12 11:16:49][INFO] Rolling table `balances` back to block 278270...
[   =] Rolling database back to block 278270...[2024-03-12 11:23:44][INFO] Rolling table `credits` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:26:46][INFO] Rolling table `debits` back to block 278270...
[  ==] Rolling database back to block 278270...[2024-03-12 11:29:43][INFO] Rolling table `messages` back to block 278270...
[  ==] Rolling database back to block 278270...[2024-03-12 11:32:48][INFO] Rolling table `order_match_expirations` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:32:50][INFO] Rolling table `order_matches` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:33:37][INFO] Rolling table `order_expirations` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:33:48][INFO] Rolling table `orders` back to block 278270...
[    ] Rolling database back to block 278270...[2024-03-12 11:36:18][INFO] Rolling table `bet_match_expirations` back to block 278270...
[  ==] Rolling database back to block 278270...[2024-03-12 11:36:19][INFO] Rolling table `bet_matches` back to block 278270...
[ ===] Rolling database back to block 278270...[2024-03-12 11:36:19][INFO] Rolling table `bet_match_resolutions` back to block 278270...
[2024-03-12 11:36:19][INFO] Rolling table `bet_expirations` back to block 278270...
[====] Rolling database back to block 278270...[2024-03-12 11:36:19][INFO] Rolling table `bets` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:36:19][INFO] Rolling table `broadcasts` back to block 278270...
[    ] Rolling database back to block 278270...[2024-03-12 11:36:20][INFO] Rolling table `btcpays` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:36:21][INFO] Rolling table `burns` back to block 278270...
[ ===] Rolling database back to block 278270...[2024-03-12 11:36:21][INFO] Rolling table `cancels` back to block 278270...
[=   ] Rolling database back to block 278270...[2024-03-12 11:36:26][INFO] Rolling table `dividends` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:36:26][INFO] Rolling table `issuances` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:37:09][INFO] Rolling table `sends` back to block 278270...
[    ] Rolling database back to block 278270...[2024-03-12 11:40:13][INFO] Rolling table `rps_match_expirations` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:40:13][INFO] Rolling table `rps_expirations` back to block 278270...
[2024-03-12 11:40:13][INFO] Rolling table `rpsresolves` back to block 278270...
[2024-03-12 11:40:13][INFO] Rolling table `rps_matches` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:40:13][INFO] Rolling table `rps` back to block 278270...
[ ===] Rolling database back to block 278270...[2024-03-12 11:40:13][INFO] Rolling table `destructions` back to block 278270...
[  ==] Rolling database back to block 278270...[2024-03-12 11:40:14][INFO] Rolling table `assets` back to block 278270...
[====] Rolling database back to block 278270...[2024-03-12 11:40:24][INFO] Rolling table `addresses` back to block 278270...
[2024-03-12 11:40:24][INFO] Rolling table `sweeps` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:40:24][INFO] Rolling table `dispensers` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:41:07][INFO] Rolling table `dispenses` back to block 278270...
[====] Rolling database back to block 278270...[2024-03-12 11:41:24][INFO] Rolling table `dispenser_refills` back to block 278270...
[=== ] Rolling database back to block 278270...[2024-03-12 11:41:24][INFO] Rolling table `transaction_outputs` back to block 278270...
[2024-03-12 11:41:24][INFO] Rolling table `transactions` back to block 278270...
[  ==] Rolling database back to block 278270...[2024-03-12 11:47:45][INFO] Rolling table `blocks` back to block 278270...
[==  ] Rolling database back to block 278270...[2024-03-12 11:49:04][INFO] Database rolled back to block_index 278270
[OK] Rolling database back to block 278270...
Rollback done in 1935.07s
[2024-03-12 11:49:05][INFO] Database version number updated.
[2024-03-12 11:49:05][INFO] Resuming parsing.
[2024-03-12 11:49:05][INFO] Starting Prefetcher process 1.
[2024-03-12 11:49:05][INFO] Starting Prefetcher process 2.
[2024-03-12 11:49:05][INFO] Starting Prefetcher process 3.
[2024-03-12 11:49:06][WARNING] Blockchain cache miss :/ Block index: 818934
[2024-03-12 11:49:18][INFO] Destruction: 1PYY9WBJpBCkVKPgttqxVFJaKRK7D7ixrZ destroyed ? 0 with tag ‘b''’(d98675d8d96b495f7e007975cb8c2db70e9b5a45a6791ff8da0e1c4a9a92e7a0) [invalid: asset invalid]
[2024-03-12 11:49:18][INFO] Destruction: 1PYY9WBJpBCkVKPgttqxVFJaKRK7D7ixrZ destroyed ? 0 with tag ‘b''’(0bf1e423e80da649c1de03b9399bb96e3d62c67a6d105db56ec6e698e5ee70e1) [invalid: asset invalid]
[2024-03-12 11:49:18][WARNING] Not storing [mpma] tx [b89e75559be6bd29bad64fbf22a020bcbcfac826406b59cef11c19591de75edd]: invalid: insufficient funds for asset CSAT, address 1EhTLJa7gf2iP35nVtfyo416icawaDHtu2 has no balance
[2024-03-12 11:49:18][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 182, in main
    server.start_all(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 496, in start_all
    blocks.follow(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 816, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 206, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(db, 'txlist_hash', previous_txlist_hash, txlist)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/check.py", line 230, in consensus_hash
    raise ConsensusError(f'Empty previous {field} for block {block_index}. Please launch a `rollback`.')
counterpartylib.lib.check.ConsensusError: Empty previous txlist_hash for block 818934. Please launch a `rollback`.
Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 182, in main
    server.start_all(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 496, in start_all
    blocks.follow(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 816, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 206, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(db, 'txlist_hash', previous_txlist_hash, txlist)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/check.py", line 230, in consensus_hash
    raise ConsensusError(f'Empty previous {field} for block {block_index}. Please launch a `rollback`.')
counterpartylib.lib.check.ConsensusError: Empty previous txlist_hash for block 818934. Please launch a `rollback`.
adam@api4:~/counterparty-core$ 
```

**Comment by ouziel-slama** [comment] 2024-03-13 14:32
should be fixed.. waiting my addrindexrs to catchup to test before closing.

**Comment by mattmarcello** [comment] 2024-03-21 14:28
I encountered what appears to be a similar error, in the context of a `kickstart`. 

Steps to reproduce:

1.  `counterparty-server kickstart --testnet`
2.  Kill process before it exits
3.  `counterparty-server kickstart --testnet`

```
counterparty-server kickstart --testnet -v
Running v10.0.0-beta.1 of Counterparty Core.
Configuration file: /home/mmarcello/.config/counterparty/server.conf
Counterparty database: /home/mmarcello/.local/share/counterparty/counterparty.testnet.db
Writing log to file: `/home/mmarcello/.cache/counterparty/log/server.testnet.log`
Writing API accesses log to file: `/home/mmarcello/.cache/counterparty/log/server.testnet.access.log`
NETWORK: Testnet
BACKEND_URL: http://rpc:*****@localhost:18332
INDEXD_URL: http://localhost:18432
RPC: http://rpc:*****@localhost:14000/rpc/
------------------------------ kickstart ------------------------------

Warnings:
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N): y
[OK] Connecting to `addrindexrs`...
[OK] Getting last known block hash...
[OK] Checking database state...
[OK] Backing up database...
[OK] Initialising database...
[OK] Starting blocks parser from block 309999...
Unhandled Exception
Traceback (most recent call last):
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 366, in run
    tx_index = parse_block(kickstart_db, cursor, block, block_parser, tx_index)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 291, in parse_block
    blocks.parse_block(kickstart_db, block['block_index'], block['block_time'])
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/blocks.py", line 206, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(db, 'txlist_hash', previous_txlist_hash, txlist)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/check.py", line 241, in consensus_hash
    raise ConsensusError(f'Empty previous {field} for block {block_index}. Please launch a `rollback`.')
counterpartylib.lib.check.ConsensusError: Empty previous txlist_hash for block 2413855. Please launch a `rollback`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmarcello/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartycli/server.py", line 220, in main
    server.kickstart(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/server.py", line 555, in kickstart
    kickstarter.run(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 406, in run
    cleanup(kickstart_db, block_parser)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 308, in cleanup
    clean_kicstart_blocks(kickstart_db)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 98, in clean_kicstart_blocks
    last_block_index_parsed = cursor.execute('''
TypeError: 'NoneType' object is not subscriptable

```

**Comment by ouziel-slama** [comment] 2024-03-22 14:04
@mattmarcello can't reproduce locally.. are you able to reproduce?

**Comment by mattmarcello** [comment] 2024-03-22 14:56
I am.  


1) Blow away counterparty.testnet.db 
```
.local/share/counterparty
❯ ls
counterparty.db
```
2) run kickstart and ctrl c while indexing blocks 

```
❯ counterparty-server kickstart --testnet
Running v10.0.0-beta.1 of Counterparty Core.
Configuration file: /home/mmarcello/.config/counterparty/server.conf
Counterparty database: /home/mmarcello/.local/share/counterparty/counterparty.testnet.db
Writing log to file: `/home/mmarcello/.cache/counterparty/log/server.testnet.log`
Writing API accesses log to file: `/home/mmarcello/.cache/counterparty/log/server.testnet.access.log`
------------------------------ kickstart ------------------------------

Warnings:
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N): y
[OK] Connecting to `addrindexrs`...
[OK] Getting last known block hash...
[OK] Checking database state...
Unhandled Exception
Traceback (most recent call last):
  File "/home/mmarcello/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartycli/server.py", line 220, in main
    server.kickstart(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/server.py", line 555, in kickstart
    kickstarter.run(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 344, in run
    kickstart_db, block_count, tx_index, last_parsed_block = intialize_kickstart_db(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 170, in intialize_kickstart_db
    fetch_blocks(cursor, bitcoind_dir, last_known_hash, first_block, spinner)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 80, in fetch_blocks
    cursor.execute(f'''INSERT INTO kickstart_blocks (block_index, block_hash, block_time, previous_block_hash, difficulty, tx_count)
KeyboardInterrupt


```

3) Run kickstart again with same args

```
❯ counterparty-server kickstart --testnet
Running v10.0.0-beta.1 of Counterparty Core.
Configuration file: /home/mmarcello/.config/counterparty/server.conf
Counterparty database: /home/mmarcello/.local/share/counterparty/counterparty.testnet.db
Writing log to file: `/home/mmarcello/.cache/counterparty/log/server.testnet.log`
Writing API accesses log to file: `/home/mmarcello/.cache/counterparty/log/server.testnet.access.log`
------------------------------ kickstart ------------------------------

Warnings:
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N): y
[OK] Connecting to `addrindexrs`...
[OK] Getting last known block hash...
[OK] Checking database state...
[OK] Backing up database...
[OK] Initialising database...
[OK] Starting blocks parser from block 309999...
Unhandled Exception
Traceback (most recent call last):
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 366, in run
    tx_index = parse_block(kickstart_db, cursor, block, block_parser, tx_index)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 291, in parse_block
    blocks.parse_block(kickstart_db, block['block_index'], block['block_time'])
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/blocks.py", line 206, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(db, 'txlist_hash', previous_txlist_hash, txlist)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/check.py", line 241, in consensus_hash
    raise ConsensusError(f'Empty previous {field} for block {block_index}. Please launch a `rollback`.')
counterpartylib.lib.check.ConsensusError: Empty previous txlist_hash for block 2523077. Please launch a `rollback`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmarcello/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartycli/server.py", line 220, in main
    server.kickstart(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/server.py", line 555, in kickstart
    kickstarter.run(
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 406, in run
    cleanup(kickstart_db, block_parser)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 308, in cleanup
    clean_kicstart_blocks(kickstart_db)
  File "/home/mmarcello/.local/lib/python3.10/site-packages/counterpartylib/lib/kickstart/__init__.py", line 98, in clean_kicstart_blocks
    last_block_index_parsed = cursor.execute('''
TypeError: 'NoneType' object is not subscriptable




```

Now there are two testnet dbs...

```
.local/share/counterparty took 2s
❯ ls
counterparty.db  counterparty.testnet.db  counterparty.testnet.db.old


```

**Comment by ouziel-slama** [comment] 2024-03-25 15:10
ok got it.. `ctrl-c` during the initialization is not correctly handled.. will fix that..

**Comment by ouziel-slama** [comment] 2024-03-28 13:33
shoud be fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1563 but will make more tests before closing.

**Comment by ouziel-slama** [comment] 2024-04-01 10:23
fixed

**Closed by ouziel-slama** 2024-04-01 10:23 UTC
Labels: bug, priority
