### ISSUE TITLE
Rust Logging Levels

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1956] opened 2024-06-24 11:57 UTC
Seems like there's an inconsistency: the log levels for the `WRITE` operations are `INFO`, but they don't show up in `STDERR` with the Python logs.

```
{"timestamp":"2024-06-01T20:49:33.792561Z","level":"INFO","fields":{"message":"Indexer initializing..."},"target":"counterparty_rs::indexer::handlers::new"}
{"timestamp":"2024-06-01T20:49:33.793194Z","level":"INFO","fields":{"message":"12 BitcoinClient workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.793217Z","level":"INFO","fields":{"message":"Connecting to database: /Users/adam/Library/Application Support/Bitcoin/fetcherdb"},
"target":"counterparty_rs::indexer::handlers::new"}
{"timestamp":"2024-06-01T20:49:33.799430Z","level":"INFO","fields":{"message":"Connected"},"target":"counterparty_rs::indexer::handlers::new"}
{"timestamp":"2024-06-01T20:49:33.799448Z","level":"INFO","fields":{"message":"Initialized"},"target":"counterparty_rs::indexer::handlers::new"}
{"timestamp":"2024-06-01T20:49:33.799598Z","level":"INFO","fields":{"message":"First database op: GetMaxBlockHeight..."},"target":"counterparty_rs::indexer::utils"
}
{"timestamp":"2024-06-01T20:49:33.799720Z","level":"INFO","fields":{"message":"First database op: GetMaxBlockHeight took 108.875µs"},"target":"counterparty_rs::ind
exer::utils"}
{"timestamp":"2024-06-01T20:49:33.799890Z","level":"INFO","fields":{"message":"First Bitcoin client op: GetBlockchainHeight..."},"target":"counterparty_rs::indexer
::utils"}
{"timestamp":"2024-06-01T20:49:33.800637Z","level":"INFO","fields":{"message":"First Bitcoin client op: GetBlockchainHeight took 734.708µs"},"target":"counterparty
_rs::indexer::utils"}
{"timestamp":"2024-06-01T20:49:33.800655Z","level":"INFO","fields":{"message":"Starting at block height: 278270"},"target":"counterparty_rs::indexer::handlers::sta
rt"}
{"timestamp":"2024-06-01T20:49:33.800666Z","level":"INFO","fields":{"message":"Targeting block height: 846104"},"target":"counterparty_rs::indexer::handlers::start
"}
{"timestamp":"2024-06-01T20:49:33.800687Z","level":"INFO","fields":{"message":"1 Producer workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.800744Z","level":"INFO","fields":{"message":"6 Fetcher workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.800782Z","level":"INFO","fields":{"message":"3 Extractor workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.800809Z","level":"INFO","fields":{"message":"1 Orderer workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.800826Z","level":"INFO","fields":{"message":"1 Writer workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.800844Z","level":"INFO","fields":{"message":"1 Reporter workers started"},"target":"counterparty_rs::indexer::workers"}
{"timestamp":"2024-06-01T20:49:33.800853Z","level":"INFO","fields":{"message":"Fetcher started"},"target":"counterparty_rs::indexer::handlers::start"}
{"timestamp":"2024-06-01T20:49:34.803619Z","level":"INFO","fields":{"message":"Write","height":278399,"max_height":846104,"progress":"9314692.21","avg_bps":"129.52
","avg_eps":"129.52","total_elapsed":"1","remaining_hrs":"1.22","f_c_len":32,"e_c_len":0,"o_c_len":0,"w_c_len":0,"r_c_len":0,"c_c_len":0,"total_num_entries":130},"
target":"counterparty_rs::indexer::workers::reporter"}
{"timestamp":"2024-06-01T20:49:35.806629Z","level":"INFO","fields":{"message":"Write","height":278597,"max_height":846104,"progress":"9314692.64","avg_bps":"163.46
","avg_eps":"163.46","total_elapsed":"2","remaining_hrs":"0.96","f_c_len":32,"e_c_len":0,"o_c_len":0,"w_c_len":0,"r_c_len":0,"c_c_len":29,"total_num_entries":328},
"target":"counterparty_rs::indexer::workers::reporter"}
{"timestamp":"2024-06-01T20:49:36.806674Z","level":"INFO","fields":{"message":"Write","height":278776,"max_height":846104,"progress":"9314693.02","avg_bps":"168.64
","avg_eps":"168.64","total_elapsed":"3","remaining_hrs":"0.93","f_c_len":32,"e_c_len":0,"o_c_len":0,"w_c_len":0,"r_c_len":7,"c_c_len":64,"total_num_entries":507},
"target":"counterparty_rs::indexer::workers::reporter"}
```

**Comment by warrenpuffett** [comment] 2024-07-05 02:16
Looked into this and find it very weird. These reporter logs are actually using `debug!` macro so their level should be "DEBUG". They are this level so that they do not appear in and pollute the STDERR logs. So actually everything is working as intended except that in the log file they are showing up as INFO level instead of DEBUG. For the file writer I am using the default, library provided, formatter. I'll keep digging though. But the intent is that we do not want these to appear in the STDERR logs. So I don't think this is a release blocking issue.

**Comment by warrenpuffett** [comment] 2024-07-07 19:26
I'm also unable to reproduce this on my machine. Maybe these logs are from an older release? These logs used to be info level but now they are debug. Anyways going to close this.

**Closed by warrenpuffett** 2024-07-07 19:26 UTC
Labels: possible bug, cli
